WebGame/Models/GameCard.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebGame.Models
{
    public class GameCard
    {
        public string Text { get; set; }

        public string No { get; set; }

        public int Id { get; set; }
    }
}

WebGame/Models/Player.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebGame.Models
{
    public class Player
    {
        /// <summary>
        /// 主要連線
        /// </summary>
        public string ConnectionId { get; set; }

        /// <summary>
        /// 玩家名稱
        /// </summary>
        public string PlayerName { get; set; }

        public string ControllerName { get; set; }

        public string RoomName { get; set; }

        /// <summary>
        /// 是否正在連線
        /// </summary>
        public bool IsConnecting { get; set; }
    }
}

WebGame/Models/PlayerRoom.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebGame.Models
{
    public class PlayerRoom
    {
        public int Id { get; set; }
        public string Name { get; set; }   
        public int TotalLimit { get; set; }
        public int TotalLimit_Str { get; set; }
        public List<Player> PlayerList { get; set; }
    }
}

WebGame/Models/RoomList.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebGame.Models
{
    public class RoomList<T> :List<PlayerRoom>
    {
        
        public new bool Add(PlayerRoom obj)
        {
            var query = base.FindAll(x => string.Equals(x.Name, obj.Name));
            if (query!=null && query.Count>0)
            {
                return false;
            }
            else
            {
                base.Add(obj);
                return true;
            }
        }
        public bool PlayerOnDisconnect(Player player)
        {
            Predicate<Player> predicate = i => i.Equals(player);
            bool isInRoom = false;
            this.ForEach(x=> {
                if (x.PlayerList.FindIndex(predicate)!=-1)
                {
                    x.PlayerList.Remove(player);
                    isInRoom = true;
                }
            });
            return isInRoom;
        }
        public void CleanRoom()
        {
            lock (this)
            {
                this.RemoveAll(x =>  x.PlayerList.Count <= 0);
            }
        }
    }
}

WebGame/Models/SelectList.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebGame.Models
{
    public class SelectList<T> : List<T>
    {
        public new bool Add(T obj)
        {
            if (obj != null&&!base.Contains(obj))
            {
                base.Add(obj);
                return true;
            }
            else
            {
                return false;
            }
        }
    }
}

WebGame/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebGame.Models;
using Microsoft.AspNet.SignalR;
using Microsoft.Ajax.Utilities;
using WebGame.SignalR;

namespace WebGame.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";
            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";
            
            return View();
        }

        [HttpPost]
        public ActionResult GameLobby(Player model)
        {            
            return View(model);           
        }
    }
}

WebGame/Controllers/OUATController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebGame.Models;
using WebGame.SignalR;
using WebLib.Utils;

namespace WebGame.Controllers
{
    public class OUATController : Controller
    {
        OUATHub OUATHub= new OUATHub();
        List<GameCard> testList = new List<GameCard>()
        {
            new GameCard{Id=1,No="t01", Text="t01T"},
            new GameCard{Id=2,No="t02", Text="t02T"},
            new GameCard{Id=3,No="t03", Text="t03T"},
        };


        public ActionResult Index(Player player)
        {
            player.ControllerName = ControllerContext.RouteData.Values["controller"].ToString();            
            return View(player);
        }
        [HttpPost]
        public JsonResult PlayerListOfRoom(string roomName)
        {
            List<Player> players = new List<Player>();
            var query = OUATHub.roomList.Find(x => string.Equals(x.Name, roomName));
            if (query != null)
            {
                players = query.PlayerList;
            }
            return new JsonResult { Data = new { data = JavaScriptObjectParser.Parse(players) } };
        }
        public ActionResult Lobby(Player player)
        {
            var query = OUATHub.playerList.Find(x => string.Equals(x.PlayerName, player.PlayerName));
            if (query != null)
            {
                OUATHub.BackToLobby(query);
            }
            return PartialView("_OUATLobby",query);
        }
        public ActionResult EnterRoom(Player player)
        {
            var query = OUATHub.playerList.Find(x => string.Equals(x.PlayerName, player.PlayerName));
            return PartialView("_OUATGame",query);
        }
    }
}

WebGame/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

WebGame/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

WebGame/Views/Home/GameLobby.cshtml
@model  WebGame.Models.Player
@{
    ViewBag.Title = "GameLobby";
}

<h2>GameLobby</h2>
<div class="form-group row">
    <div class="col-sm-4">
        <div class="row form-group">
            <label class="col-sm-4">玩家名稱</label>
            <div class="col-sm-4">
                @Html.DisplayTextFor(model => model.PlayerName)
            </div>
        </div>
    </div>
    <div class="col-sm-8"></div>
</div>


<!--TODO Web/GameLobby/做成Partial View-->
<div class="form-group row">
    <div class="panel-default panel">
        <div class="col-sm-3">
            <div class="row">
                <label>從前從前</label>
                <p class="pull-right" id="pGameLobby_OUAT_TotalNum"></p>
                <label class="pull-right">人數</label>
            </div>
            <a class="row" href="@Url.Action("Index","OUAT",new { PlayerName = Model.PlayerName})">
                <div class="divGameImg" style="height:300px;background-color:#2caa9f;"></div>
            </a>
        </div>      
    </div>
</div>
@section scripts{
    <script>

    </script>
}

WebGame/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <div class="form-group">
        <h3>注意事項</h3>
        <span>1.</span><label>請先輸入玩家名稱。</label>
    </div>
</div>
@using (Html.BeginForm("GameLobby", "Home", FormMethod.Post, new { Id = "formPlayerData" }))
{
    @Html.Hidden("PlayerName", null, new { Id = "hidePlayerName" });
}
<div class="row form-group">
    <div class="col-sm-4">
        <div class="row form-group">
            <label class="col-sm-4 control-label">名稱</label>
            <div class="col-sm-8">          
                <input type="text" id="txtPlayerName" />
            </div>
        </div>
        <div class="row form-group">
            <div class="col-sm-4">             
                <button class=" btn btn-success" id="btnEnter">進入</button>
            </div>
            <div class="col-sm-8">
         
            </div>
        </div>
    </div>
    <div class="col-sm-8"></div>
</div>


@section scripts{
  
    <script>
        $('#btnEnter').on('click', function () {
            //var player = $.connection.webGameHub;
            //$.connection.hub.start().done(function () {
            //    player.server.connectToHub($('#txtPlayerName').val());
            //});
            $('#hidePlayerName').val($('#txtPlayerName').val());
            $('#formPlayerData').submit();
        });

    </script>
}

@*<div class="row">
        <div class="col-md-4">
            <h2>Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </div>
        <div class="col-md-4">
            <h2>Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </div>
        <div class="col-md-4">
            <h2>Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </div>
    </div>*@

WebGame/Views/OUAT/Index.cshtml
@model  WebGame.Models.Player
@{
    ViewBag.Title = "Index";
}
<div id="@Model.ControllerName">
    @Html.Partial("~/Views/OUAT/_OUATLobby.cshtml", Model)
</div>


@section scripts{
<script>
     var player = $.connection.oUATHub;
    if (!@Json.Encode(Model.IsConnecting)) {
        $.connection.hub.start().done(function () {
            var data = {};
            data["PlayerName"] = '@Model.PlayerName';
            data["ControllerName"] = '@Model.ControllerName';
            player.server.connectToHub(data).done();

            player.server.currentRoomList().done(function (response) {
                var data = eval(response.Data.data);
                JsGridRoomList(data);
            });
        });
    }
            //防止重複ConnectionId
    player.client.duplicateConnectionId = async function ()
    {
        window.location = '@Url.Action("Index","Home")';
        alert("重複Id,請再試一次");
    }
    player.client.getOnlinePlayerNumber = async function (num)
    {
        $('#onlinePlayerNum').text(num);
    }
        player.client.currentRoomList = async function (response)
        {
            if (response.Data.hasRoom != null && response.Data.hasRoom) {
                var data = eval(response.Data.data);
                JsGridRoomList(data);
            } else {
                var data = [];
                JsGridRoomList(data);
            }
    };

    function JsGridRoomList (data) {
        $.each(data, function (value, index) {
            this.TotalLimit_Str = this.PlayerList.length + "/" + this.TotalLimit;
        });
        $('#jsgrid_OUAT_Room').jsGrid("option", "data", data);
    }

    $("#jsgrid_OUAT_Room").jsGrid({
        width: "100%",
        autoload: false,
        paging: true,
        pageSize: 10,
        pageLoading: true,
        pagerContainer: "#jsgrid_OUAT_Room_Pager",
        data: [],
        rowClick: function (item) {
            $('#modal_lbRoomName').text(item.item.Name);
            $('#modal_lbTotalLimit').text(item.item.TotalLimit_Str);
            $('#jsgrid_PlayerList').jsGrid("loadData");
            $('#modal_divPlayerRoomDetail').modal('show');
        },
        fields: [
            { name: "Name", title: '房間名稱', type: "text", width: 60, align: "center" },
            { name: "TotalLimit_Str", title: '房間人數', type: "text", width: 40, align: "right" },
            {
                name: "Name", title: '進入房間',
                itemTemplate: function (value, item) {
                    var $result = $([]);
                    return jsGridTemplate.customButton(value, item, null, '進入').attr('class','btn btn-success');
                },
                width: 50, align: "center"
            },
        ],
        controller: {
            loadData: function (filter) {
                var d = $.Deferred();
                var rtn = $.ajax({
                    url: '@Url.Action("QueryForAdjustment", "Quotation")',
                    data: {
                        Pager: {
                            CurrentPageNumber: filter.pageIndex - 1,
                            PageSize: filter.pageSize,
                        },
                        ProjectName: $('#txtProjectName').val(),
                        ExamineeName: $('#txtExamineeName').val(),
                        IdNo: $('#txtIdentityCard').val(),
                        OtherIdType:$('#ddlOtherIdType').val(),
                        OtherIdNo :$('#txtOtherIdNo').val(),
                    }
                }).done(function (response) {

                    var data = eval(response.data);
                    d.resolve({
                        data: data,
                        itemsCount: response.itemsCount,
                    });
                    });
                return d.promise();
            }
        }
    });

</script>
}

WebGame/Views/OUAT/_OUATGame.cshtml
@model  WebGame.Models.Player
<div>
    <h3>test</h3>  
    <button id="btnLeaveRoom" class="btn btn-danger" >離該</button>
    
</div>

<script>
    $('#btnLeaveRoom').on("click", function () {
        @*window.location = '@Url.Action("Index",Model.ControllerName)';*@
        var data = {};
        data["PlayerName"] = '@Model.PlayerName';
        data["ControllerName"] = '@Model.ControllerName';
        data["IsConnecting"] = true;
        $.ajax({
            url: '@Url.Action("Lobby",Model.ControllerName)',
            data: data,
        }).done(function (response) {
            $('#@Model.ControllerName').html(response);
        });
    });

    player.client.currentRoomList = async function (response) {
        if (response.Data.data != typeof null) {
            var data = eval(response.Data.data);
            JsGridRoomList(data);
        }
    };

    function JsGridRoomList(data) {
        $.each(data, function (value, index) {
            this.TotalLimit_Str = this.PlayerList.length + "/" + this.TotalLimit;
        });
        $('#jsgrid_OUAT_Room').jsGrid("option", "data", data);
    }
</script>

WebGame/Views/OUAT/_OUATLobby.cshtml
@model  WebGame.Models.Player
<h2>Welcome To Once Upon A Time , PlayerName : @Html.DisplayTextFor(model => model.PlayerName)</h2>
<div class="form-group row">
    <label class="control-label col-sm-2">在限總人數</label>
    <div class="col-sm-4">
        <p id="onlinePlayerNum"></p>
    </div>
</div>
<div class="form-group row">
    <div class="col-sm-6">
        <div id="divOUAT_Menu">
            <div class="form-group row">
                <button class="btn btn-default" id="btnOUAT_CreateRoom">創建</button>
            </div>
            <div class="form-group row">
                <button class="btn btn-default">test</button>
            </div>
        </div>
    </div>
    <div class="col-sm-6">
        <div id="jsgrid_OUAT_Room"></div>
        <div id="jsgrid_OUAT_Room_Pager"></div>
    </div>
</div>

<div class="modal fade" id="modal_divCreateRoom" role="dialog">
    <div class="modal-dialog modal-xl" style="width:60%;">
        <div class="modal-content">
            <div class="modal-header">
                <h4>Create New Room</h4>
            </div>
            <div class="modal-body">
                <div class="form-group row">
                    <div class="col-sm-6">
                        <label class="control-label col-sm-6">房間名稱 :</label>
                        <input type="text" id="modal_txtRoomName" class="col-sm-6 form-control" />
                    </div>
                    <div class="col-sm-6">
                        <label class="control-label col-sm-6">房間人數 :</label>
                        <input type="number" min="1" value="1" id="modal_numRoomName" class="form-control col-sm-6" />
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button id="modal_btnConfirm" type="button" class="btn btn-default pull-right">確定</button>
            </div>
        </div>
    </div>
</div>
@Html.Partial("~/Views/Shared/_PlayerRoomDetail.cshtml", Model)


<script>
    $(document).ready(function () {

        $('#btnOUAT_CreateRoom').on("click", function () {
            $('#modal_divCreateRoom').modal("show");
        });
        $('#modal_btnConfirm').on("click", function () {
            var data = {};
            data["Name"] = $('#modal_txtRoomName').val();
            data["TotalLimit"] = $('#modal_numRoomName').val();
            player.server.createRoom(data).done(function (response) {
                if (response.Data.result) {
                    var data = eval(response.Data.data);
                    if (data.length>0) {
                        JsGridRoomList(data);
                    }
                    $.ajax({
                        url: '@Url.Action("EnterRoom",Model.ControllerName)',
                        data:
                        {
                            PlayerName: '@Model.PlayerName',
                            ControllerName: '@Model.ControllerName',
                        },
                    }).done(function (response) {
                        $('#@Model.ControllerName').html(response);
                    });
                } else {
                    alert("已有相同房間請重新命名");
                };
                hideModal("#modal_divCreateRoom");
            });
        });
    });
    @*var player = $.connection.oUATHub;
    if (!@Json.Encode(Model.IsConnecting)) {
        $.connection.hub.start().done(function () {
            var data = {};
            data["PlayerName"] = '@Model.PlayerName';
            data["ControllerName"] = '@Model.ControllerName';

            player.server.currentRoomList().done(function (response) {
                var data = eval(response.Data.data);
                JsGridRoomList(data);
            });
        });
    }*@

        //防止重複ConnectionId
    @*player.client.duplicateConnectionId = async function () {
        window.location = '@Url.Action("Index","Home")';
        alert("重複Id,請再試一次");
    }
    player.client.getOnlinePlayerNumber = async function (num)
    {
        $('#onlinePlayerNum').text(num);
    }
    player.client.currentRoomList = async function (response) {
        if (response.Data.data != typeof null) {
            var data = eval(response.Data.data);
            JsGridRoomList(data);
        }
    };*@


    //init
    //function ReEnterLobby() {
    //    player.server.getOnlinePlayerNumberSelf().done(function (response) {
    //        $('#onlinePlayerNum').text(response);
    //    });
    //    CurrentRoomList();
    //}

    //function CurrentRoomList() {
    //    player.server.currentRoomList().done(function (response) {
    //        var data = eval(response.Data.data);
    //        JsGridRoomList(data);
    //    });
    //}

    function JsGridRoomList (data) {
        $.each(data, function (value, index) {
            this.TotalLimit_Str = this.PlayerList.length + "/" + this.TotalLimit;
        });
        $('#jsgrid_OUAT_Room').jsGrid("option", "data", data);
    }

    $("#jsgrid_OUAT_Room").jsGrid({
        width: "100%",
        autoload: false,
        paging: true,
        pageSize: 10,
        pageLoading: true,
        pagerContainer: "#jsgrid_OUAT_Room_Pager",
        data: [],
        rowClick: function (item) {
            $('#modal_lbRoomName').text(item.item.Name);
            $('#modal_lbTotalLimit').text(item.item.TotalLimit_Str);
            $('#jsgrid_PlayerList').jsGrid("loadData");
            $('#modal_divPlayerRoomDetail').modal('show');
        },
        fields: [
            { name: "Name", title: '房間名稱', type: "text", width: 60, align: "center" },
            { name: "TotalLimit_Str", title: '房間人數', type: "text", width: 40, align: "right" },
            {
                name: "Name", title: '進入房間',
                itemTemplate: function (value, item) {
                    var $result = $([]);
                    return jsGridTemplate.customButton(value, item, null, '進入').attr('class','btn btn-success');
                },
                width: 50, align: "center"
            },
        ],
        controller: {
            loadData: function (filter) {
                var d = $.Deferred();
                var rtn = $.ajax({
                    url: '@Url.Action("QueryForAdjustment", "Quotation")',
                    data: {
                        Pager: {
                            CurrentPageNumber: filter.pageIndex - 1,
                            PageSize: filter.pageSize,
                        },
                        ProjectName: $('#txtProjectName').val(),
                        ExamineeName: $('#txtExamineeName').val(),
                        IdNo: $('#txtIdentityCard').val(),
                        OtherIdType:$('#ddlOtherIdType').val(),
                        OtherIdNo :$('#txtOtherIdNo').val(),
                    }
                }).done(function (response) {

                    var data = eval(response.data);
                    d.resolve({
                        data: data,
                        itemsCount: response.itemsCount,
                    });
                    });
                return d.promise();
            }
        }
    });
</script>

WebGame/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 我的 ASP.NET 應用程式</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/jquery.signalR-2.3.0.min.js"></script>
    @*<script type="text/javascript" src="signalr/hubs"></script>*@
    <script src="~/signalr/hubs"></script>
    <script src='/signalr/js'></script>
    @Styles.Render("~/Scripts/jsGridCSS")
    @Scripts.Render("~/Scripts/jsGrid")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/Scripts/WebJS")
    <!-- Page JS-->
    @*<script src="~/Scripts/Pages/custom_jsGrid.js"></script>*@
    @*<script src="~/Scripts/Pages/base.js"></script>
    <script src="~/Scripts/Pages/utils.js"></script>*@
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("應用程式名稱", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("首頁", "Index", "Home")</li>
                    <li>@Html.ActionLink("從前從前", "Index", "OUAT")</li>
                    @*<li>@Html.ActionLink("關於", "About", "Home")</li>
                        <li>@Html.ActionLink("連絡人", "Contact", "Home")</li>*@
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - CopyRight Dann All Rights Reserved.</p>
        </footer>
    </div>
    @RenderSection("scripts", required: false)
</body>
</html>

WebGame/Views/Shared/_PlayerRoomDetail.cshtml
@model  WebGame.Models.Player
<div class="modal fade" id="modal_divPlayerRoomDetail">
    <div class="modal-dialog modal-xl" style="width:80%">
        <div class="modal-content">
            <div class="modal-header">
                <h4>Player List</h4>
            </div>
            <div class="modal-body">
                <div class="form-group row">
                    <label class="control-label col-sm-3">房間名稱 :</label>
                    <label class="control-label col-sm-4" id="modal_lbRoomName"></label>
                    <label class="control-label col-sm-3">房間數量 :</label>
                    <label class="control-label col-sm-2" id="modal_lbTotalLimit"></label>
                </div>
                <div class="form-group row">
                    <div id="jsgrid_PlayerList"></div>
                </div>
            </div>
            <div class="modal-footer">
                <button id="modal_btnEnterRoom" type="button" class="btn btn-success pull-right">進入</button>
            </div>
        </div>
    </div>
</div>
<script>
    $(function () {
        $('#modal_btnEnterRoom').on("click", function () {
            if (player != typeof undefined) {
                var data = {};
                data["PlayerName"] = '@Model.PlayerName';
                data["ControllerName"] = '@Model.ControllerName';
                data["RoomName"] =  $('#modal_lbRoomName').text();

                player.server.enterRoom(data).done(function (response) {                  
                    if (response.Data.result) {
                        $.ajax({
                            type: "GET",
                            url: '@Url.Action("EnterRoom", Model.ControllerName)',
                            data: {
                                PlayerName: '@Model.PlayerName',
                                ControllerName: '@Model.ControllerName',
                                //RoomName: $('#modal_lbRoomName').text(),
                            },
                        }).done(function (response) {                         
                            $('#@Model.ControllerName').html(response);
                        });
                    } else {
                        alert('無法進入遊戲房間');
                    }
                    hideModal("#modal_divPlayerRoomDetail");
                });
            } else {
                alert('未與Server連接');
            }
        });
    });

    $('#jsgrid_PlayerList').jsGrid({
        width: "100%",
        autoload: false,
        paging: false,
        pageLoading: false,
        data:[],
        rowClick: function (item) {
        },
        fields: [
            { name: "PlayerName", title: '玩家名稱', type: "text", width: 60, align: "center" },
            //{ name: "TotalLimit_Str", title: '房間人數', type: "text", width: 40, align: "right" },
            //{
            //    name: "Name", title: '進入房間',
            //    itemTemplate: function (value, item) {
            //        var $result = $([]);
            //        return jsGridTemplate.customButton(value, item, null, '進入').attr('value', value);
            //    },
            //    width: 50, align: "center"
            //},
        ],
        controller: {
            loadData: function (filter) {
                var d = $.Deferred();
                var rtn = $.ajax({
                    type:'POST',
                    url: '@Url.Action("PlayerListOfRoom", "OUAT")',
                    data: {
                        //Pager: {
                        //    CurrentPageNumber: filter.pageIndex - 1,
                        //    PageSize: filter.pageSize,
                        //},
                        roomName: $('#modal_lbRoomName').text(),
                    },
                }).done(function (response) {
                    var data = eval(response.data);
                    //$('#jsgrid_PlayerList').jsGrid('option', 'data', data);
                    $('#jsgrid_PlayerList').jsGrid("option", "data", data);
                    //d.resolve({
                    //    data: eval(response.data),
                    //    itemsCount: response.itemsCount,
                    //});
                    });
                //return d.promise();
            }
        }
    });
</script>